language: elixir
elixir:
  - 1.3.2
otp_release:
  - 19.0

sudo: required
dist: trusty

# Install dependencies
addons:
  apt:
    packages:
    - bc
    - libssl-dev

# Cache downloaded files between builds
cache:
    directories:
      - $HOME/.nerves/cache/buildroot

env:
  - NERVES_SYSTEM_CACHE=none NERVES_SYSTEM_COMPILER=local PACKAGE=nerves_system_ev3 REPO=mobileoverlord/$PACKAGE

before_install:
    - wget https://github.com/elixir-lang/elixir/releases/download/v$ELIXIR_VERSION/Precompiled.zip
    - unzip -d elixir Precompiled.zip

before_script:
    - export PATH=`pwd`/elixir/bin:$PATH

script:
  - mix archive.install https://github.com/nerves-project/archives/raw/master/nerves_bootstrap.ez --force
  - mix compile

# Deploy the build products
before_deploy:
    - mix compress.nerves_system
    - deps/nerves_system_br/scripts/ci-deploy.sh
deploy:
  # Deploy tagged releases to GitHub
  - provider: releases
    api_key: $GITHUB_API_KEY
    file:
      - "artifacts/$CI_SYSTEM_NAME-$TRAVIS_TAG.tar.gz"
      - "artifacts/$CI_SYSTEM_NAME-$TRAVIS_TAG.fw"
    skip_cleanup: true
    overwrite: true
    on:
      repo: $REPO
      tags: true

# Display build log on failure
after_failure:
    - tail -n 1000 build.log
