language: elixir
elixir:
  - 1.3.2
otp_release:
  - 19.0

# Cache downloaded files between builds
cache:
    directories:
      - $HOME/.nerves/cache/buildroot

env:
  - ELIXIR_VERSION=1.3.2

script:
  - mix compile
